# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
- group: secrets

stages:
  - stage: Test
    jobs:
      - job: Codebeamer
        displayName: "CodeBeamer upload"
        steps:
          - script: |
              echo "Empty Job"
